name: Build

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
        env:
          REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
      - run: npm install
      - run: npm run build
