name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    name: Upload to Amazon S3
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
          aws-region: us-east-1
        env:
          REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
      - run: npm install
      - run: npm run build
      - name: Copy files to the test website with the AWS CLI
        run: |
          aws s3 sync build/ s3://la-cabana-avicola-client
